site_name: INNERDARK
theme: 
  name: 'material'
  palette:
    primary: custom
    accent: custom
    scheme: slate
  font:
    text: 'Oswald Light'
    code: 'Oswald Thin'
  features:
    - navigation.expand
    - navigation.path
    - search
  language: ru
  logo: images/innerdark-logo.ico
  favicon: images/innerdark-favico.png
extra_css:
  - stylesheets/extra.css
extra:
  article_nav_top: false
  article_nav_bottom: false
  history_buttons: false
plugins:
  - search
  - tags
  - obsidian-bridge
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html